stages:
  - dockerize
  - deploy

#DOCKERIZING

# dockerize_static:
#   stage: dockerize
#   image: docker
#   variables:
#     GIT_STRATEGY: clone
#     DOCKER_DRIVER: overlay2
#   services:
#     - docker:dind
#   script:
#     - docker build -t bmstu-structure-view ./assets
#   after_script:
#     - docker login --username=$DOCKER_USER --password=$DOCKER_PASSWD
#     - docker tag bmstu-structure-view $DOCKER_USER/bmstu-structure-view
#     - docker push $DOCKER_USER/bmstu-structure-view

dockerize_api:
  stage: dockerize
  image: docker
  variables:
    GIT_STRATEGY: clone
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - docker build -t sdal-notifier-bot .
  after_script:
    - docker login --username=$DOCKER_USER --password=$DOCKER_PASSWD
    - docker tag sdal-notifier-bot $DOCKER_USER/sdal-notifier-bot
    - docker push $DOCKER_USER/sdal-notifier-bot

# DEPLOYING

deploy:
  stage: deploy
  image: ictu/sshpass
  variables:
    GIT_STRATEGY: clone
  dependencies:
    # - dockerize_static
    - dockerize_api
  script:
    # - sshpass -p "$SDAL_PASSWD" ssh -oStrictHostKeyChecking=no root@95.216.188.201 docker pull almosvirog/bmstu-structure-view
    # - sshpass -p "$SDAL_PASSWD" ssh -oStrictHostKeyChecking=no root@95.216.188.201 docker rm -f bmstu-structure-view || true
    # - sshpass -p "$SDAL_PASSWD" ssh -oStrictHostKeyChecking=no root@95.216.188.201 docker run -d -p 80:80 --name bmstu-structure-view almosvirog/bmstu-structure-view

    - sshpass -p "$SDAL_PASSWD" ssh -oStrictHostKeyChecking=no root@95.216.188.201 docker pull almosvirog/sdal-notifier-bot
    - sshpass -p "$SDAL_PASSWD" ssh -oStrictHostKeyChecking=no root@95.216.188.201 docker rm -f sdal-notifier-bot || true
    - sshpass -p "$SDAL_PASSWD" ssh -oStrictHostKeyChecking=no root@95.216.188.201 docker run -d -p 3010:3010 --name sdal-notifier-bot almosvirog/sdal-notifier-bot
